#!/usr/bin/env python3

import os
import sys

profileid = sys.argv[1]

profilepath = os.path.expanduser('~/.local/share/feren-store-ice/firefox/' + str(profileid))
chromepath = os.path.expanduser('~/.local/share/feren-store-ice/firefox/' + str(profileid) + '/chrome')
path = os.path.dirname(chromepath)

os.system('mkdir -p ' + chromepath)
os.system('echo "#nav-bar, #identity-box, #tabbrowser-tabs, #TabsToolbar { visibility: collapse !important; }" > ' + chromepath + '/userChrome.css')
os.system('echo "user_pref(\\"app.shield.optoutstudies.enabled\\", false);" >> ' + profilepath + '/user.js')
os.system('echo "user_pref(\\"browser.cache.disk.enable\\", false);" > ' + profilepath + '/user.js')
os.system('echo "user_pref(\\"browser.cache.disk.capacity\\", 0);" >> ' + profilepath + '/user.js')
os.system('echo "user_pref(\\"browser.cache.disk.filesystem_reported\\", 1);" >> ' + profilepath + '/user.js')
os.system('echo "user_pref(\\"browser.cache.disk.smart_size.enabled\\", false);" >> ' + profilepath + '/user.js')
os.system('echo "user_pref(\\"browser.cache.disk.smart_size.first_run\\", false);" >> ' + profilepath + '/user.js')
os.system('echo "user_pref(\\"browser.cache.disk.smart_size.use_old_max\\", false);" >> ' + profilepath + '/user.js')
os.system('echo "user_pref(\\"browser.ctrlTab.previews\\", true);" >> ' + profilepath + '/user.js')
os.system('echo "user_pref(\\"browser.tabs.warnOnClose\\", false);" >> ' + profilepath + '/user.js')
os.system('echo "user_pref(\\"browser.newtabpage.activity-stream.asrouter.userprefs.cfr.addons\\", false);" >> ' + profilepath + '/user.js')
os.system('echo "user_pref(\\"browser.newtabpage.activity-stream.asrouter.userprefs.cfr.features\\", false);" >> ' + profilepath + '/user.js')
os.system('echo "user_pref(\\"browser.newtabpage.activity-stream.feeds.section.highlights\\", false);" >> ' + profilepath + '/user.js')
os.system('echo "user_pref(\\"browser.newtabpage.activity-stream.feeds.section.topstories\\", false);" >> ' + profilepath + '/user.js')
os.system('echo "user_pref(\\"browser.newtabpage.activity-stream.feeds.snippets\\", false);" >> ' + profilepath + '/user.js')
os.system('echo "user_pref(\\"browser.newtabpage.activity-stream.feeds.topsites\\", false);" >> ' + profilepath + '/user.js')
os.system('echo "user_pref(\\"browser.search.suggest.enabled\\", false);" >> ' + profilepath + '/user.js')
os.system('echo "user_pref(\\"datareporting.healthreport.uploadEnabled\\", false);" >> ' + profilepath + '/user.js')
os.system('echo "user_pref(\\"datareporting.dataSubmissionPolicyAcceptedVersion\\", 2);" >> ' + profilepath + '/user.js')
os.system('echo "user_pref(\\"datareporting.policy.dataSubmissionPolicyAcceptedVersion\\", "2");" >> ' + profilepath + '/user.js')
os.system('echo "user_pref(\\"privacy.trackingprotection.enabled\\", true);" >> ' + profilepath + '/user.js')
os.system('echo "user_pref(\\"privacy.trackingprotection.socialtracking.enabled\\", true);" >> ' + profilepath + '/user.js')
os.system('echo "user_pref(\\"privacy.donottrackheader.enabled\\", true);" >> ' + profilepath + '/user.js')
os.system('echo "user_pref(\\"toolkit.telemetry.reportingpolicy.firstRun\\", false);" >> ' + profilepath + '/user.js')
os.system('echo "user_pref(\\"trailhead.firstrun.didSeeAboutWelcome\\", false);" >> ' + profilepath + '/user.js')
os.system('echo "user_pref(\\"toolkit.legacyUserProfileCustomizations.stylesheets\\", true);" >> ' + profilepath + '/user.js')
os.system('cp -n /usr/lib/feren-store-new/ice/firefox/search.json.mozlz4 ' + profilepath + '/search.json.mozlz4')
os.system('cp -n /usr/lib/feren-store-new/ice/firefox/places.sqlite ' + profilepath + '/places.sqlite')
